# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: D3add3d on GitHub
email: d3add3d@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My lair :P
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://d3add3d.net" # the base hostname & protocol for your site
twitter_username: D3add3d
github_username:  d3add3d
keybase_username: d3add3d

# Build settings
markdown: kramdown
